title: Practice Webpage 
author: Fabadiculous
email: ...
description: > # this means to ignore newlines until "baseurl:"
  A practice webpage using github pages

# social links
github_username:  Fabadiculous

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
